version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: money-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 2004
      MYSQL_DATABASE: money_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
